config/routes.rb
Rails.application.routes.draw do
  resources :votes
  resources :links
  resources :users

  get  'login', to: 'sessions#new',    as: 'login'
  post 'login', to: 'sessions#create', as: 'create_session'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'links#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :votes#, dependent: :destroy

  def self.select_links
    all.map { |link| [link.title, link.id] }
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :links

  def self.select_users
    all.map { |user| [user.name, user.id] }
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :link
  belongs_to :user



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :current_user
  # Run 'current_user' before every controller action

  def current_user
    if @current_user.nil?
      if session[:user_id].present?
        @current_user = User.find(session[:user_id])
      end
    else
      @current_user
    end
  end

  def authenticate_user!
    unless current_user
      flash[:alert] = "You must be logged in to do that."
      redirect_to login_path
    end
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    authenticate_user!
    @link = Link.new
    @all_users = User.select_users
  end

  # GET /links/1/edit
  def edit
    authenticate_user!
    @link = Link.find(params[:id])
    @all_users = User.select_users
  end

  # POST /links
  # POST /links.json
  def create
    authenticate_user!
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    authenticate_user!
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    authenticate_user!
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :body, :user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if user && user.authenticate(params[:password])
      # Save the user id inside a browser cookie.
      # Specifically, the rails 'session'. This is how we keep the user
      # logged in when they navigate around our website.
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Successfully logged in!'
    else
      # If user's login doesn't work, send them back to the login form.
      flash[:alert] = "Username or Email did not match"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Successfully Logged Out. Goodbye!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]


  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      #session[:user_id] = user.id
      redirect_to root_path, notice: 'User created!'
    else
      flash[:alert] = 'Errors Occured.'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  def upvote
  end

  def downvote
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
    @votes = Vote.all
  end

  # GET /votes/new
  def new
    @vote = Vote.new
    @all_users = User.select_users
    @all_links = Link.select_links
  end

  # GET /votes/1/edit
  def edit
    @all_users = User.select_users
    @all_links = Link.select_links
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:upvote, :downvote, :link_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    unless @current_user.nil?
      true
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wreckkit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Wreckkit', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'New Link', new_link_path %></li>
        <li><%= link_to 'Votes', votes_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Sign Up', new_user_path %></li>
        <% if logged_in? %>
          <li><%= link_to 'Logout', logout_path %></li>
        <% else %>
          <li><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container-fluid">
  <%= yield %>
</div>

<footer>
  Made by Mike Pitre
</footer>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-sm-8 col-sm-offset-4">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field col-sm-8 col-sm-offset-4">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field col-sm-8 col-sm-offset-4">
    <%= f.label :user_id %><br>
    <%= f.select :user_id, @all_users %>
  </div>
  <div class="actions col-sm-2 col-sm-offset-4 submit">
    <%= f.submit "submit", class: "btn btn-primary" %>
  </div>


<% end %>

app/views/links/edit.html.erb
<h1 class="col-sm-8 col-sm-offset-4">Editing Link</h1>

<%= render 'form' %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <h1 class="col-sm-8 col-sm-offset-2 links_title">Links</h1>
</div>


    <% @links.each do |link| %>
        <h5 class="col-sm-8 col-sm-offset-2"><%= link.title %> by <%= link.user.name %></h5>
        <p class="col-sm-8 col-sm-offset-2"><%= link.body %></p>
        <div class="row">
          <div class="col-sm-4 col-sm-offset-2 sed link-options">
            <%= link_to 'Show', link %>
            <%= link_to 'Edit', edit_link_path(link) %>
            <%= link_to 'Delete', link, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
    <% end %>

<br>

app/views/links/new.html.erb
<h1 class="col-sm-8 col-sm-offset-4 title">New Link</h1>

<%= render 'form' %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<h5 class="col-sm-8 col-sm-offset-2">
  <%= @link.title %> by <%= @link.user.name %>
</h5>

<p class="col-sm-8 col-sm-offset-2">
  <%= @link.body %>
</p>

<div class="row">
  <div class="col-sm-4 col-sm-offset-2 sed">
    <p><%= button_to 'Vote', new_vote_path, :class => "btn btn-primary", :method => :get %></p>
  </div>
</div>

<div class="row">
  <div class="col-sm-4 col-sm-offset-2 sed">
    <%= link_to 'Edit', edit_link_path(@link) %> |
    <%= link_to 'Back', links_path %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-sm-8 col-sm-offset-4">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field col-sm-8 col-sm-offset-4">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field col-sm-8 col-sm-offset-4">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field col-sm-8 col-sm-offset-4">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions col-sm-2 col-sm-offset-4 submit">
    <%= f.submit "submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="field col-sm-8 col-sm-offset-4">New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-sm-8 col-sm-offset-4">
    <%= f.label :upvote %><br>
    <%= f.number_field :upvote %>
  </div>
  <div class="field col-sm-8 col-sm-offset-4">
    <%= f.label :downvote %><br>
    <%= f.number_field :downvote %>
  </div>
  <div class="field col-sm-8 col-sm-offset-4">
    <%= f.label :link_id, "Which link do you want to vote for?" %><br>
    <%= f.select :link_id, @all_links %>
  </div>
  <div class="actions col-sm-2 col-sm-offset-4 submit">
    <%= f.submit "submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="col-sm-8 col-sm-offset-4 votes_title">Listing Votes</h1>

<table class="col-sm-8 col-sm-offset-4">
  <thead>
    <tr>
      <th>Upvotes</th>
      <th>Downvotes</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.upvote %></td>
        <td><%= vote.downvote %></td>
        <td><%= link_to vote.link.title, links_path %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/votes/new.html.erb
<h1 class= "col-sm-8 col-sm-offset-4">New Vote</h1>

<%= render 'form' %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Upvote:</strong>
  <%= @vote.upvote %>
</p>

<p>
  <strong>Downvote:</strong>
  <%= @vote.downvote %>
</p>

<p>
  <strong>Link:</strong>
  <%= @vote.link.title %>
</p>

<p><%= link_to 'Vote for this Link', new_vote_path %></p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>